$dataDir = "D:\Tawreed\egypt-cities-main"
$outputFile = "D:\Tawreed\TawreedAPI\Tawreed.Infrastructure\Data\SeedData\RegionSeedData.cs"

# Read JSON files
$govs = Get-Content "$dataDir\governorates.json" -Encoding UTF8 | ConvertFrom-Json
$centers = Get-Content "$dataDir\center_govs.json" -Encoding UTF8 | ConvertFrom-Json
$cityCenters = Get-Content "$dataDir\city_centers.json" -Encoding UTF8 | ConvertFrom-Json

$rootGuid = "00000000-0000-0000-0000-000000000000"

function MakeGuid($prefix8, $id) {
    return "$prefix8-0000-0000-0000-$($id.ToString().PadLeft(12, '0'))"
}

function Escape($s) {
    return $s.Replace("\", "\\").Replace("""", "\""").Replace("`r", "").Replace("`n", " ").Trim()
}

$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("// <auto-generated/>")
$lines.Add("#nullable enable")
$lines.Add("using Tawreed.Domain.Entities;")
$lines.Add("using Tawreed.Domain.Enums;")
$lines.Add("")
$lines.Add("namespace Tawreed.Infrastructure.Data.SeedData;")
$lines.Add("")
$lines.Add("public static class RegionSeedData")
$lines.Add("{")
$lines.Add("    private static readonly DateTime _date = new(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);")
$lines.Add("")
$lines.Add("    public static List<Region> All =>")
$lines.Add("    [")

# Egypt root
$lines.Add("        new Region { Id = Guid.Parse(""$rootGuid""), NameAr = ""\u0645\u0635\u0631"", NameEn = ""Egypt"", Type = RegionType.Country, IsActive = true, CreatedAt = _date },")

# Governorates
foreach ($gov in $govs) {
    $gid = [int]$gov.id
    $guid = MakeGuid "00000000" $gid
    $nameAr = Escape $gov.name_ar
    $nameEn = Escape $gov.name_en
    $lines.Add("        new Region { Id = Guid.Parse(""$guid""), NameAr = ""$nameAr"", NameEn = ""$nameEn"", Type = RegionType.Governorate, ParentId = Guid.Parse(""$rootGuid""), IsActive = true, CreatedAt = _date },")
}

# Centers
foreach ($c in $centers) {
    $cid = [int]$c.id
    $guid = MakeGuid "00000001" $cid
    $nameAr = Escape $c.name_ar
    $nameEn = Escape $c.name_en
    $parentGuid = MakeGuid "00000000" ([int]$c.governorate_id)
    $lines.Add("        new Region { Id = Guid.Parse(""$guid""), NameAr = ""$nameAr"", NameEn = ""$nameEn"", Type = RegionType.City, ParentId = Guid.Parse(""$parentGuid""), IsActive = true, CreatedAt = _date },")
}

# City centers (villages)
foreach ($cc in $cityCenters) {
    $ccid = [int]$cc.id
    $guid = MakeGuid "00000002" $ccid
    $nameAr = Escape $cc.name_ar
    $nameEn = Escape $cc.name_en
    $parentGuid = MakeGuid "00000001" ([int]$cc.center_gov_id)
    $lines.Add("        new Region { Id = Guid.Parse(""$guid""), NameAr = ""$nameAr"", NameEn = ""$nameEn"", Type = RegionType.Village, ParentId = Guid.Parse(""$parentGuid""), IsActive = true, CreatedAt = _date },")
}

$lines.Add("    ];")
$lines.Add("}")

# Write file as UTF-8 without BOM
$joined = $lines -join "`r`n"
[System.IO.File]::WriteAllText($outputFile, $joined, [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $($lines.Count) lines -> $outputFile"
Write-Host "Entries: 1 root + $($govs.Count) governorates + $($centers.Count) centers + $($cityCenters.Count) city centers = $(1 + $govs.Count + $centers.Count + $cityCenters.Count) total"
